# These limits are used by MoveIt and augment/override the definitions in my_panda_description.
# (the limits refer to effort velotiy lower upper tags of the joints definition)
# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most use
# cases. For specific applications, higher values might lead to better execution performance.

joint_limits:
  panda_joint1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  panda_joint7:
    has_acceleration_limits: true
    max_acceleration: 5.0
